name: CI
on: 
   workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE    
